media:
  input: public/uploads
  output: /uploads

content:
  - name: blog
    label: Blog Posts
    type: collection
    path: src/content/blog
    filename: "{primary}.md"
    view:
      fields: [title, pubDate, draft]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, required: true }
      - { name: pubDate, label: Publish Date, type: date, required: true }
      - { name: updatedDate, label: Updated Date, type: date }
      - { name: heroImage, label: Hero Image, type: image }
      - { name: draft, label: Draft, type: boolean, default: false }
      - { name: body, label: Body, type: rich-text, required: true }